name: Scheduler (Every 10 minutes)

# Spec: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule
# For debug: https://crontab.guru/
on:
  schedule:
    - cron: '*/10 * * * *' # Every 10 minutes
#    - cron: '0 * * * *'   # Every 1 hour

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 💎 Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: false
        #ruby-version: 3.1 # Not necessary if .ruby-version is given

    - name: 🔔 Exec wufoo2mattermost task
      env:
        TZ: 'Asia/Tokyo'
        FILEPATH: 'entry_id_list.yaml'
        WUFOO_API_USERNAME:  ${{ secrets.WUFOO_API_USERNAME }}
        WUFOO_API_PASSWORD:  ${{ secrets.WUFOO_API_PASSWORD }}
        WUFOO_API_SUBDOMAIN: ${{ secrets.WUFOO_API_SUBDOMAIN }}
        WUFOO_API_FORM_ID:   ${{ secrets.WUFOO_API_FORM_ID }}
        MATTERMOST_ENDPOINT: ${{ secrets.MATTERMOST_ENDPOINT }}
      run: |
        bundle exec rake notify_wufoo_entry_to_mattermost
        if [ -n "$(git status ${{ env.FILEPATH }} --porcelain)" ]; then
          git config --global user.name  "Yohei Yasukawa"
          git config --global user.email "yohei@yasslab.jp"
          git add ${{ env.FILEPATH }}
          git commit -m '🤖 Update current YAML data by GitHub Actions'
          git push
        fi
