name: Scheduler (Every 10 minutes)

on:
  # The shortest interval you can run scheduled workflows is once every 5 minutes.
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    - cron: '*/10 * * * *' # Every 10 minutes

  # Allows you to run this workflow manually from the Actions tab
  # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: ☑️ Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: 💎 Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        #ruby-version: 3.2 # Not necessary if .ruby-version is given

    - name: 🔔 Exec wufoo2mattermost task
      env:
        TZ: 'Asia/Tokyo'
        FILEPATH: 'entry_id_list.yaml'
        WUFOO_API_USERNAME:  ${{ secrets.WUFOO_API_USERNAME }}
        WUFOO_API_PASSWORD:  ${{ secrets.WUFOO_API_PASSWORD }}
        WUFOO_API_SUBDOMAIN: ${{ secrets.WUFOO_API_SUBDOMAIN }}
        WUFOO_API_FORM_ID:   ${{ secrets.WUFOO_API_FORM_ID }}
        MATTERMOST_ENDPOINT: ${{ secrets.MATTERMOST_ENDPOINT }}
      run: |
        bundle exec rake notify_wufoo_entry_to_mattermost
        if [ -n "$(git status ${{ env.FILEPATH }} --porcelain)" ]; then
          git config --global user.name  "Yohei Yasukawa"
          git config --global user.email "yohei@yasslab.jp"
          git checkout main
          git add ${{ env.FILEPATH }}
          git commit -m '🤖 Update current YAML data by GitHub Actions'
          git push origin main
        fi
